"""
PDF Generator Utilities — ReportLab se professional PDFs banao
Yeh file Lambda Layer mein rahegi.
Dono Member 3 ke Lambda functions yeh use karenge:
  - timeline_pdf_generator
  - complaint_generator

INSTALL: pip install reportlab -t layers/pdf-layer/python/
"""
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table,
    TableStyle, HRFlowable, PageBreak
)
from io import BytesIO
from datetime import datetime

# ── Brand Colors ──
BRAND_DARK   = colors.HexColor('#1a237e')   # Deep Indigo
BRAND_MED    = colors.HexColor('#283593')   # Medium Indigo
BRAND_LIGHT  = colors.HexColor('#e8eaf6')   # Light Indigo background
BRAND_ACCENT = colors.HexColor('#ff6f00')   # Amber accent
TEXT_DARK    = colors.HexColor('#212121')
TEXT_MUTED   = colors.HexColor('#757575')

def _get_styles():
    """Document styles define karo"""
    base = getSampleStyleSheet()
    return {
        'title': ParagraphStyle(
            'DocTitle', parent=base['Title'],
            fontSize=20, textColor=BRAND_DARK,
            spaceAfter=6, spaceBefore=0,
            fontName='Helvetica-Bold'
        ),
        'subtitle': ParagraphStyle(
            'Subtitle', parent=base['Normal'],
            fontSize=11, textColor=BRAND_MED,
            spaceAfter=4
        ),
        'heading': ParagraphStyle(
            'Heading', parent=base['Heading2'],
            fontSize=12, textColor=BRAND_DARK,
            spaceBefore=12, spaceAfter=6,
            fontName='Helvetica-Bold'
        ),
        'normal': ParagraphStyle(
            'Body', parent=base['Normal'],
            fontSize=10, leading=15,
            textColor=TEXT_DARK, spaceAfter=4,
            alignment=TA_JUSTIFY
        ),
        'normal_left': ParagraphStyle(
            'BodyLeft', parent=base['Normal'],
            fontSize=10, leading=14,
            textColor=TEXT_DARK
        ),
        'bold': ParagraphStyle(
            'Bold', parent=base['Normal'],
            fontSize=10, leading=14,
            fontName='Helvetica-Bold',
            textColor=TEXT_DARK
        ),
        'small': ParagraphStyle(
            'Small', parent=base['Normal'],
            fontSize=8, textColor=TEXT_MUTED,
            alignment=TA_CENTER
        ),
        'table_header': ParagraphStyle(
            'TH', parent=base['Normal'],
            fontSize=9, textColor=colors.white,
            fontName='Helvetica-Bold',
            alignment=TA_CENTER
        ),
        'table_cell': ParagraphStyle(
            'TC', parent=base['Normal'],
            fontSize=9, leading=12,
            textColor=TEXT_DARK
        ),
        'disclaimer': ParagraphStyle(
            'Disclaimer', parent=base['Normal'],
            fontSize=8, textColor=TEXT_MUTED,
            alignment=TA_CENTER, spaceAfter=0
        )
    }

def _add_header(story, styles, title: str, subtitle: str = '', ref: str = ''):
    """Document header add karo"""
    # Top bar
    header_data = [[
        Paragraph('⚖ NYAYA MITRA', ParagraphStyle(
            'Logo', fontSize=14, textColor=colors.white,
            fontName='Helvetica-Bold'
        )),
        Paragraph(
            f'<font color="white">Ref: {ref}</font>' if ref else '',
            ParagraphStyle('Ref', fontSize=9, textColor=colors.white, alignment=2)
        )
    ]]
    header_table = Table(header_data, colWidths=[10*cm, 7*cm])
    header_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), BRAND_DARK),
        ('TOPPADDING', (0, 0), (-1, -1), 10),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
        ('LEFTPADDING', (0, 0), (0, -1), 12),
        ('RIGHTPADDING', (-1, 0), (-1, -1), 12),
    ]))
    story.append(header_table)
    story.append(Spacer(1, 0.3*cm))
    story.append(Paragraph(title, styles['title']))
    if subtitle:
        story.append(Paragraph(subtitle, styles['subtitle']))
    story.append(HRFlowable(width='100%', thickness=2, color=BRAND_DARK))
    story.append(Spacer(1, 0.3*cm))

def _add_footer(story, styles, ref: str = ''):
    """Document footer add karo"""
    story.append(Spacer(1, 0.5*cm))
    story.append(HRFlowable(width='100%', thickness=0.5, color=TEXT_MUTED))
    story.append(Spacer(1, 0.2*cm))
    date_str = datetime.now().strftime('%d %B %Y, %H:%M')
    footer_text = f"Generated by Nyaya Mitra — {date_str}"
    if ref:
        footer_text += f" | Ref: {ref}"
    story.append(Paragraph(footer_text, styles['small']))
    story.append(Paragraph(
        "This document is for informational purposes only and does not constitute legal advice. "
        "Please consult a qualified lawyer for your specific situation.",
        styles['disclaimer']
    ))


# ════════════════════════════════════════════
#              TIMELINE PDF
# ════════════════════════════════════════════

def generate_timeline_pdf(data: dict) -> bytes:
    """
    Timeline PDF banao.
    data format:
    {
        'timeline_id': str,
        'issue_type': str,
        'timeline': [
            {'date': str, 'event': str, 'legal_significance': str, 'category': str}
        ],
        'gaps': [str],
        'complainant_name': str (optional)
    }
    """
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        leftMargin=2*cm, rightMargin=2*cm,
        topMargin=1.5*cm, bottomMargin=2*cm
    )
    styles = _get_styles()
    story  = []

    issue_display = data.get('issue_type', 'General').replace('_', ' ').title()
    ref = data.get('timeline_id', '')[:8].upper()

    _add_header(
        story, styles,
        'LEGAL TIMELINE',
        f"Issue Type: {issue_display}  |  Generated: {datetime.now().strftime('%d %b %Y')}",
        ref
    )

    if data.get('complainant_name'):
        story.append(Paragraph(f"<b>Prepared for:</b> {data['complainant_name']}", styles['normal_left']))
        story.append(Spacer(1, 0.2*cm))

    # ── Events Table ──
    events = data.get('timeline', [])
    if events:
        story.append(Paragraph('CHRONOLOGICAL EVENTS', styles['heading']))

        rows = [[
            Paragraph('Date', styles['table_header']),
            Paragraph('Event', styles['table_header']),
            Paragraph('Legal Significance', styles['table_header'])
        ]]

        for e in events:
            rows.append([
                Paragraph(e.get('date', 'Unknown'), styles['table_cell']),
                Paragraph(e.get('event', ''), styles['table_cell']),
                Paragraph(e.get('legal_significance', ''), styles['table_cell'])
            ])

        t = Table(rows, colWidths=[3.2*cm, 8*cm, 5.5*cm])
        t.setStyle(TableStyle([
            ('BACKGROUND',    (0, 0), (-1, 0),  BRAND_DARK),
            ('ROWBACKGROUNDS',(0, 1), (-1, -1),  [colors.white, BRAND_LIGHT]),
            ('GRID',          (0, 0), (-1, -1),  0.5, colors.HexColor('#bdbdbd')),
            ('VALIGN',        (0, 0), (-1, -1),  'TOP'),
            ('TOPPADDING',    (0, 0), (-1, -1),  5),
            ('BOTTOMPADDING', (0, 0), (-1, -1),  5),
            ('LEFTPADDING',   (0, 0), (-1, -1),  6),
            ('RIGHTPADDING',  (0, 0), (-1, -1),  6),
        ]))
        story.append(t)
        story.append(Spacer(1, 0.3*cm))

    # ── Gaps Section ──
    gaps = data.get('gaps', [])
    if gaps:
        story.append(Paragraph('INFORMATION GAPS (Collect These)', styles['heading']))
        gaps_data = []
        for g in gaps:
            gaps_data.append([
                Paragraph('⚠', ParagraphStyle('W', fontSize=12, textColor=BRAND_ACCENT)),
                Paragraph(g, styles['normal_left'])
            ])
        if gaps_data:
            gaps_table = Table(gaps_data, colWidths=[0.8*cm, 15.9*cm])
            gaps_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#fff8e1')),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#ffe082')),
                ('TOPPADDING', (0, 0), (-1, -1), 5),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
                ('LEFTPADDING', (0, 0), (-1, -1), 6),
                ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ]))
            story.append(gaps_table)

    _add_footer(story, styles, ref)
    doc.build(story)
    return buffer.getvalue()


# ════════════════════════════════════════════
#              COMPLAINT PDF
# ════════════════════════════════════════════

def generate_complaint_pdf(data: dict, complaint_text: str) -> bytes:
    """
    Complaint PDF banao.
    data format:
    {
        'tracking_number': str,
        'complaint_type': str,
        'complaint_type_display': str
    }
    complaint_text: Bedrock se generate hua formal complaint text
    """
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        leftMargin=3*cm, rightMargin=2.5*cm,
        topMargin=2*cm, bottomMargin=2.5*cm
    )
    styles = _get_styles()
    story  = []

    tracking    = data.get('tracking_number', 'N/A')
    type_display= data.get('complaint_type_display', 'Complaint')

    _add_header(
        story, styles,
        type_display.upper(),
        f"Generated by Nyaya Mitra AI Legal Assistant",
        tracking
    )

    # ── Tracking box ──
    tracking_data = [[
        Paragraph('Tracking Number', styles['bold']),
        Paragraph(tracking, ParagraphStyle(
            'TN', fontSize=12, textColor=BRAND_DARK, fontName='Helvetica-Bold'
        ))
    ]]
    tracking_table = Table(tracking_data, colWidths=[5*cm, 11.7*cm])
    tracking_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), BRAND_LIGHT),
        ('GRID', (0, 0), (-1, -1), 1, BRAND_MED),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ('LEFTPADDING', (0, 0), (-1, -1), 10),
    ]))
    story.append(tracking_table)
    story.append(Spacer(1, 0.5*cm))

    # ── Complaint text ──
    for line in complaint_text.strip().split('\n'):
        stripped = line.strip()
        if not stripped:
            story.append(Spacer(1, 0.15*cm))
            continue

        is_heading = (stripped.isupper() and len(stripped) > 3) or \
                     (stripped.endswith(':') and len(stripped.split()) <= 5)

        if is_heading:
            story.append(Paragraph(stripped, styles['heading']))
        else:
            story.append(Paragraph(stripped, styles['normal']))

    _add_footer(story, styles, tracking)
    doc.build(story)
    return buffer.getvalue()
